[package]
name = "emotions"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "emotions from feelingswheel.com as a rust crate"
repository = "https://github.com/abhillman/emotions-rs"
readme = "README.md"
keywords = ["emotions", "feelings"]
